sudo: required
services:
  - docker

before_install:
  - docker build -t kianyang28/docker-react -f Dockerfile.dev .

script:
  - docker run kianyang28/docker-react npm run test -- --coverage

deploy:
  provide: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-855840985103"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"